### ISSUE TITLE
Game froze breaking a double glass slab

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#10]
`Minecraft v1.14.4`
`Forge v28.2.0`
`Double Slabs v1.0.1`
[`Vanilla Things v0.4.6`](https://www.curseforge.com/minecraft/mc-mods/vanilla-things)

After creating a double glass slab using the mod Vanilla Things, I tried to break it, but my game froze.
[Here](https://gist.github.com/WenXin20/267d3df1fc038b66d6a902de0d9c4b0b) is the log.

The double glass slab was also opaque instead of clear, ~but I'm not sure which mod had the oversight.~ After removing this mod, I could see that the double glass slab is normally clear, but this mod may not account for opacity.

**Comment by CJMinecraft01** [comment]
Yes that is correct, the mod assumes that all slabs aren't transparent which is an oversight on my part. I do plan to rework the rendering of slabs to take this into account in the near future but in the mean time, I'll work on fixing that issue you had

**Comment by WenXin20** [comment]
Thanks!

**Comment by CJMinecraft01** [comment]
Ok so I've been working on this for quite a few hours and have got it working! The only issue is, is that because the double slab block is dynamic I am going to have to make a compromise.
You see, to make a block that is transparent render the sides of neighbouring blocks, I have to tell the game that the block is not solid and that the block should always rendering neighbouring sides, even if the block actually isn't made of transparent slabs. This would be awful on performance on a large scale as minecraft naturally culls blocks which are next to each other and shouldn't be visible but there is no way for me to check whether the block contains a transparent slab or not.
The alternative to this, is to make only the sides transparent that have a double slab block next to them, meaning that against regular blocks the double slab appears fine when at least one half is transparent however when against double slabs blocks that are full, we get the x-ray effect.
![2020-03-18_13 50 44](https://user-images.githubusercontent.com/13885569/76967591-8c7b1280-691f-11ea-9074-7ada4f964af3.png)
![2020-03-18_13 50 52](https://user-images.githubusercontent.com/13885569/76967597-8dac3f80-691f-11ea-8b16-ee098f476453.png)
![2020-03-18_13 50 57](https://user-images.githubusercontent.com/13885569/76967599-8e44d600-691f-11ea-919b-a7be36467403.png)

Because of this, I'm going to use the latter. Whilst we have the x-ray effect which isn't ideal, the effect is a lot less on performance than the first method. The only alternative would be to rewrite how I render the double slabs which isn't ideal at the moment.
Just thought I'd give you an update

**Comment by WenXin20** [comment]
Alright, whichever is best. :)
I wasn't using it to build anything, just testing the mod out.

**Comment by CJMinecraft01** [comment]
Should be fixed in the latest version!
