### ISSUE TITLE
Incompatibility with Optifines Connected Textures

### ISSUE THREAD

**Issue by STAUDER02** [CJMinecraft01/DoubleSlabs#106]
Using a custom resource pack that edits slab connected textures using double slabs disables those visuals
![image](https://user-images.githubusercontent.com/39335834/90808658-ada5bc00-e320-11ea-8126-4dbaf4678c80.png)
these are all stacked slabs but the carved ones have been placed before enabling doubleslabs

**Comment by STAUDER02** [comment]
![image](https://user-images.githubusercontent.com/39335834/90809394-b054e100-e321-11ea-981d-5f6d8c39b76e.png)
here is the same problem with biome specific textures for vertical slabs

**Comment by STAUDER02** [comment]
Well apparently it is possible to use vertical connected textures as shown in the screenshots but it is "complicated" and horizontal textures don't work with that technique

**Comment by CJMinecraft01** [comment]
I believe that some of this issue is due to the nature of how Double Slabs stores and displays slabs. The mod renders the two slabs separately meaning that connected texture on the full block is lost likely to be broken. Would you mind providing a link to download this resource pack so that I can test it? I may find a way to render the full block when both slabs are of the same type

**Comment by STAUDER02** [comment]
it is the conquest resource pack
https://www.planetminecraft.com/texture-pack/conquest-32x32/

**Comment by CJMinecraft01** [comment]
Hi there! Thanks again for reporting this and apologies for the delay. I believe that this should now be fixed since when two slabs of the same type are combined, the double slab model is used.
