### ISSUE TITLE
When using slabs from another mod called "Block craftery" they appear invisible!

### ISSUE THREAD

**Issue by BluEagle-Dev** [CJMinecraft01/DoubleSlabs#108]
So basically block craftery is a mod that adds some framed pieces(stairs, blocks, slabs) that you can right with a block to give it the texture of the block.

When i make a full block out of those slabs they appear invisible, same with vertical slabs!

AND, if you break a block made out of 2 vertical slabs of that mod the game crashes when you go near it! Creating an crash loop.
The only way to get out of that crash loop is quickly getting out of the arrea before the world loads, and exploding or getting rid of that remaining slab from a big distance

(in my case i used an NFL or idk how is it called from tinkers construct, basically a throwable tnt exploding thingy)

**Comment by CJMinecraft01** [comment]
Hi, thanks for the bug report. Would you mind showing the crash log so that I can investigate what is causing the crash. I am aware of the rendering issue, in fact this has been an issue since the start of the mod but I have recently had an idea which may fix the issue so I'll try my best to do that for you!

**Comment by BluEagle-Dev** [comment]
Ok i will recreate the crash in another new world and send the crash log!

**Comment by BluEagle-Dev** [comment]
Here is the crash log:  https://pastebin.com/KzTLAmwr

**Comment by CJMinecraft01** [comment]
This should be fixed in the latest version :)
