### ISSUE TITLE
Crafting override

### ISSUE THREAD

**Issue by A-T-L-A-S** [CJMinecraft01/DoubleSlabs#124]
Double slabs seem to override any crafting recipe that includes just one slab. Meaning if there is exactly one slab in the crafting the result will always be its's vertical variant; no matter which other items are present.

![grafik](https://user-images.githubusercontent.com/39281662/93348919-1e17fe00-f837-11ea-8582-f5ce5eb7aaef.png)

Minecraft version: 1.15.2  forge-31.2.36
Mod version: DoubleSlabs-1.15-2.11.5

I have quark installed and suspect that it might be a part of this problem but I have no clue tbh.

EDIT:
The issue seems to be a thing with create. I notice that this bug only appears when an item from create is present as well.
I will see if I can get some more info on that.

**Comment by gamrguy** [comment]
According to the code, this would be because the recipe doesn't abort when checking the crafting inventory for valid slabs. I don't know why this would only trigger with Create items for you - it would seem as if this would happen in any arrangement where there is any number of crafting inputs but only one valid slab stack.

The relevant code, from what I can tell, is here: https://github.com/CJMinecraft01/DoubleSlabs/blob/a6fd9b25aaf2f12f05b1e7dfef0bdb2795ad69c8/src/main/java/cjminecraft/doubleslabs/common/crafting/VerticalSlabRecipe.java#L21

**Comment by CJMinecraft01** [comment]
Hi, thanks for the issue and the responses. It seems that @gamrguy is correct in that the recipe does not check for any invalid items apart from multiple stacks which is an oversight on my behalf, sorry about that. I will get that patched and updated as soon as possible. Sorry for the inconvenience.

**Comment by CJMinecraft01** [comment]
Fixed in the latest version. Thanks for your patience

**Comment by A-T-L-A-S** [comment]
> 
> 
> Fixed in the latest version. Thanks for your patience

WOW - That was fast! 🤩 Thank you so much
