### ISSUE TITLE
Game Crashes when placing slabs/destroying slabs

### ISSUE THREAD

**Issue by ashton727** [CJMinecraft01/DoubleSlabs#144]
Crash report: https://pastebin.com/vxWj4W7D

Not sure if it a mod conflict, but the game consistently crashes when placing or destroying slabs especially vertical slabs and double layered slabs

**Comment by mlysle** [comment]
I have basically the same crash with the same error. My world is now broken because of it.
Unfortunately I can't share the crash log because my log is so long that it exceeds the maximum file size on pastebin/hastebin.

edit: I can confirm this only happens in BoP worlds. Doesn't matter the biome, the world has to be generated with BoP.

**Comment by IskallDoe** [comment]
I have the same problem has the above

**Comment by Orinai** [comment]
Can confirm the same issue on my end. I can upload my crash log, but it's pretty much identical.

also worth noting: since the error has something to do with dim7 (same dimension twilight forest uses by default), I've noticed it causing issues with the twilight forest mod, where the twilight portal just spits me back out into the overworld as if it were the twilight forest. Removing double slabs has fixed both issues.

**Comment by TheidenHD** [comment]
https://github.com/TheidenHD/DoubleSlabs/releases/tag/0.11.1

**Comment by CJMinecraft01** [comment]
Thanks for the bug report. I'm extremely sorry in the delayed response and inactivity. I believe this crash is a duplicate of #140. Please use that issue to post further updates. Thank you again, and my sincerest apologies for the inconvenience.
