### ISSUE TITLE
Craftable vertical slabs

### ISSUE THREAD

**Issue by disastercube** [CJMinecraft01/DoubleSlabs#147]
Minecraft 1.12.2
------------------------------

Vertical slabs are currently very unstable. Issues range from crashes to various placing problems such as: 
-missing textures, 
-not being able to place horizontal slabs on blocks that you can interact with **(to place a block from a crafting table you'd need to shift so the UI wouldn't open, but with the config "sneaking" option, such things are not possible with slabs)**, 
-no vertical slab placement in liquids.

This mod approaches vertical slabs in such way, that the players vision depends on the slabs position (this can also make building with them difficult).

_**Not being able to place a horizontal slab with config sneaking option turned on:**_
![2020-10-16_15 43 31](https://user-images.githubusercontent.com/62697421/96267299-ef24b180-0fc7-11eb-8653-e5a922ea76a4.png)

**_Missing texture:_**
![2020-10-16_15 42 14](https://user-images.githubusercontent.com/62697421/96267447-12e7f780-0fc8-11eb-9b53-87f6f5953e04.png)

A simple solution to this problems would be to implement new **block/blocks** to the mod and that would be **"craftable vertical slabs"**. Simply put three wooden blocks as if you would craft a slab but in a vertical position and there you have it.
This would remove crashes from the complex coding that is behind vertical slabs, missing textures, UI objects problems and in liquid placement (also ads easier compatibilities with other mods that add wood variants).

**Comment by CJMinecraft01** [comment]
Hi there! Thank you for your suggestion, in order for the vertical slabs to work with **any** regular horizontal slab, they must be dynamically created. Unfortunately the issue you are witnessing is related to how I try to be more efficient when rendering vertical slabs by culling faces you shouldn't see; however there was an issue in the old version. This has now been fixed in the latest version, apologies for the delay
