### ISSUE TITLE
Potential crash with Astral Sorcery

### ISSUE THREAD

**Issue by pm065** [CJMinecraft01/DoubleSlabs#189]
Crash log: https://paste.ubuntu.com/p/gVb7kTCTJF/
Happened when I removed and replaced the vertical slab repeatedly. I'm on the latest version that doesn't have the vertical campfire problem. (Speaking of which, is there a way to add a blacklist? The vertical campfires just look dumb tbh)

**Comment by CJMinecraft01** [comment]
Hi there! Thanks for the reporting this, I will investigate and try to resolve this as soon as I can :) regarding the vertical campfires, these can be disabled in the server config by adding the block name to the vertical slab blacklist (the server config is in the world folder). The reason they exist is because I support placing campfires on regular horizontal slabs but as a side effect, they can be placed vertically.

**Comment by tweakbsd** [comment]
Can confirm this bug. Current Astral Sorcery version and your mod doesn't work well together. The end result is that some form of Double Slab TileEntity crashes the game. My Crashlog is almost identical to the already uploaded one the crash comes from here:

cjminecraft.doubleslabs.common.tileentity.SlabTileEntity.func_226984_a_(SlabTileEntity.java:107)

**Comment by CJMinecraft01** [comment]
Hey there! Thank you again for reporting this, would you mind testing this in the latest version? I believe that this should be fixed :)
