### ISSUE TITLE
Crashes with terrafirmacraft slabs.

### ISSUE THREAD

**Issue by Pival81** [CJMinecraft01/DoubleSlabs#2]
I tried placing a tfc slab on top of another tfc slab and it crashed.

https://paste.dimdev.org/zuhumalavi.rb

**Comment by Pival81** [comment]
Actually, this just happened with thaumcraft slabs too.

**Comment by CJMinecraft01** [comment]
Okay, while investigating this issue, the source of this issue is due to the fact that I'm accessing a private field which I've made public using an access transformer. I'll continue to have a look but if this is happening with multiple mods, be sure to send the log file, that would be super helpful! Thanks for your patience

**Comment by CJMinecraft01** [comment]
Should be resolved in the latest update
