### ISSUE TITLE
[Suggestion] Alternative Texture for Vertical Slabs [Long Post]

### ISSUE THREAD

**Issue by SpiderKolo** [CJMinecraft01/DoubleSlabs#54]
So... I really like your Vertical Slabs a lot! I'm currently using Quarks Vertical Slabs, but with this feature I consider completely swapping to this since it expands on Slabs way more.

There is one thing which personally doesn't fit in my mind, but it's mostly an opinion, nor an actual issue:
I'm not sure if I like rotation of texture which is implemented when placing vertical slabs.
At least on some blocks - notably just planks really, because it's either:
I don't notice on other blocks, because their texture is the same on all sides anyway or their texture isn't different enough to make it look odd;
Or I do notice and they actually fit better that way. A good example would be Smooth Stone Slabs - they actually look amazing with rotational textures... and it also makes sense and gives some new options when building with.
In case of Planks I don't like they can be vertical, altho in my defense mostly because I have separate block which is just... vertical planks. I like having that block in case I feel like I want to use different rotation of planks.

So since the feature looks great on some blocks, neutral on others and on very few... well, it's just that I don't like it specifically, I had an idea which might make slabs overall better for building:

**How about a configuration which let's you decide which slabs textures would be applied in more... I will call it "Lazy" way.**
It could work like this (in picture I'm using Quark for visualization):

It's visible notably on smaller sides of slabs, the sides with size of full block's side seems to be unaffected by rotation...

This is current way of texturing Vertical Slabs:
![image](https://user-images.githubusercontent.com/62638498/84091946-41d8d600-a9f6-11ea-97e4-25b8744ea5ee.png)
It works amazingly on Slabs with textures which would look otherwise a bit worse if not textured "Properly".

Smooth Stone Slab (Vanilla), Glass Slabs (Glasscuter by MrCrayfish) - those were textured with them being slabs in mind. Not specifically for this mod, but because this mod rotates textures, they look very good.

This is the "Lazy" way of texturing Vertical Slabs (Quark for Visualization):
![image](https://user-images.githubusercontent.com/62638498/84091960-4ef5c500-a9f6-11ea-9593-2576de09ab63.png)

This method doesn't rotate texture with block, but instead applies un-rotated textures as they would normally go on full block... but on slab.

It's very good on blocks which don't have texture designed to be in specific shape, but because of this, they can be used neutrally in any shape.
That is until you randomly rotate it in comparison with another block with the same texture, then it might be confusing with different but similar block or annoy when looking at it while comparing to other, surrounding it blocks.

Stone (Vanilla), Cobblestone (Vanilla), Terracotta (again Vanilla, except this block get's slabs and stairs from mods) - those blocks were not designed to fit specific block shape - if you repeat it continuously on a wall, there isn't defined "end" of texture. Obviously that doesn't mean they don't end, they just create an illusion of being that mass of one big thing or many small things.

Alternatively blocks which are cut just right can be also used in any typical building shape (Slabs, Stairs).
Any type of Planks (Vanilla and most mods), Dark Prismarine (Vanilla), Purpur Block (Vanilla), Stone Bricks (Vanilla) are examples of a block which are visibly segmented, but still can work in many shapes with "Lazy" applying of textures.

**So... which one to use?**
Both are needed, obviously, since they work better with different blocks, **but how to decide which slab should be textured in what way?**
I'm suggesting Configuration option with list of blocks which are affected either way and a simple rule where you just write which group it defines. That way, a modpack maker can decide on each of the blocks himself.

While I think theoretically it might not be a difficult to implement change, I don't create mods so I can't tell if that's really the case.

What you think about this idea I wrote?

**Comment by CJMinecraft01** [comment]
This is a fantastic idea! I completely agree regarding the rotation of the texture. For most blocks, I tested using stone brick slabs, this tiles perfectly but for planks it is clear that it does not.

I also love the idea of using a configuration option, as it is merely an aesthetical change which is dependent on the user.

Regarding how I would implement this, I'm not too sure. At the moment, I am physically rotating the original slab model so that it is vertical which gives the rotation effect you showed in your images. To not rotate the texture but rotate the model may be a bit harder and I may opt to choose a different approach for blocks which have this "lazy" rendering enabled.

I understand that you don't create mods but I still wanted to explain the process of how I might be able to make it work.

The alternate approach for "lazy" blocks is to have a predefined vertical slab model and to simply switch the textures for the block which means that the model is not rotated. I haven't tested this idea yet to see if it actually will work but it's just an idea that I'm throwing out there.

Again, thanks for the suggestion, I'll take a look at what I can do!

**Comment by CJMinecraft01** [comment]
![image](https://user-images.githubusercontent.com/13885569/87534426-e8676500-c68d-11ea-85c7-86a0e7ca1e8f.png)
I think I've just managed to implement this finally so in the next update you should have this feature! By default all of the plank slabs will use the lazy model rendering

**Comment by CJMinecraft01** [comment]
Added in the latest version!
