### ISSUE TITLE
Crash with WAILA

### ISSUE THREAD

**Issue by T4ge** [CJMinecraft01/DoubleSlabs#7]
https://paste.dimdev.org/ezipewoxaj.mccrash
Don't have much information at this time regarding this, just forwarding the crash from a user of the modpack this is in.

**Comment by T4ge** [comment]
![Screenshot_20191212-234018_Discord](https://user-images.githubusercontent.com/8440488/70754871-9e558400-1d38-11ea-9d94-26071faf3fcd.jpg)
Additional info from user

**Comment by CJMinecraft01** [comment]
Would you happen to have a link to the modpack so I can try to recreate the bug?

**Comment by T4ge** [comment]
https://www.curseforge.com/minecraft/modpacks/dojopack
There you go :)

**Comment by T4ge** [comment]
Any news on this issue or estimates for a potential fix?

**Comment by CJMinecraft01** [comment]
Hi, sorry for the delay.. I've took a look into this and I haven't been able to recreate this issue. What I will do, is I will place an extra precaution at the position that the error occurred so that this issue should not happen again. The new version should release shortly. If it does happen again, be sure to let me know!
