### ISSUE TITLE
Compatibility request for Create

### ISSUE THREAD

**Issue by Barerock** [CJMinecraft01/DoubleSlabs#83]
Using the non-standard placements for slabs on moving constructs causes the slabs to lose their texture and become pink/black checkered blocks. This isn't an issue with Quark vertical slabs, so maybe find pointers there? Here's a reference to the issue on Create's page. Also I mixed this and Klee slabs up and made a couple reports with those. These are the real ones.
Forge: 31.2.23
MC: 1.15.2
Create: 0.2.4d
Double Slabs: 2.7.6
![image](https://user-images.githubusercontent.com/38869993/87589587-7144c780-c6b3-11ea-8b81-99b8415ea128.png)
The top block next to the wool is a normal slab, the rest are Quark vertical slabs.

https://github.com/Creators-of-Create/Create/issues/409

Thanks!

**Comment by CJMinecraft01** [comment]
Thanks for the report, I have a suspicion it may be due to something on the other mods side and how they render the constructs as the vertical slabs use something known as model data which allows any slab to be a vertical slab. When there is no model data, it reverts to the missing model texture hence the appearance shown. I'll take a look into this though and get back to you!

**Comment by Barerock** [comment]
Huh. That sounds super cool. I figured you used something like that since there aren't extra blocks and it's a lightweight mod. Thanks for the quick response!

**Comment by CJMinecraft01** [comment]
Hi there! Sorry for the extreme delay, I believe Create has fixed this :)
